services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bankpass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:                 # <- add this block
      test: ["CMD-SHELL", "pg_isready -U bank -d bankdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  ml:
    build:
      context: ./ml-service
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      retries: 5

  backend:
    build:
      context: ./backend
    depends_on:                  # <- change to health-based depends_on
      db:
        condition: service_healthy
      ml:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_DATASOURCE_USERNAME: bank
      SPRING_DATASOURCE_PASSWORD: bankpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      ML_BASE_URL: http://ml:8000
      # Snowflake configuration (update with your actual values)
      SNOWFLAKE_URL: jdbc:snowflake://uinmrec-gp26051.snowflakecomputing.com
      SNOWFLAKE_USERNAME: SHAYLINZ
      SNOWFLAKE_PASSWORD: Nim@219121912191
      SNOWFLAKE_DATABASE: BKRISK_DB
      SNOWFLAKE_SCHEMA: CORE
      SNOWFLAKE_WAREHOUSE: COMPUTE_WH

volumes:
  pgdata:
