services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bankpass
    ports:
      - "5433:5432"        # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data

  ml:
    build:
      context: ./ml-service
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8000/health"]
      interval: 10s
      retries: 5

  backend:
    build:
      context: ./backend
    depends_on:
      - db
      - ml
    ports:
      - "8080:8080"
    environment:
      # talk to Postgres container (service name is "db")
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_DATASOURCE_USERNAME: bank
      SPRING_DATASOURCE_PASSWORD: bankpass
      # create/update tables automatically in this dev stack
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # talk to ML container (service name is "ml")
      ML_BASE_URL: http://ml:8000

volumes:
  pgdata:
