spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bank
    password: bankpass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
