spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bankdb
    username: bank
    password: CHANGEME
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

ml:
  base-url: http://localhost:8000
