server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/bankdb}
    username: ${SPRING_DATASOURCE_USERNAME:bank}
    password: ${SPRING_DATASOURCE_PASSWORD:bankpass}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# ML service base URL (Docker service name, not localhost)
ml:
  base-url: ${ML_BASE_URL:http://ml:8000}

# Snowflake configuration
snowflake:
  url: ${SNOWFLAKE_URL:jdbc:snowflake://your-account.snowflakecomputing.com}
  username: ${SNOWFLAKE_USERNAME:your-username}
  password: ${SNOWFLAKE_PASSWORD:your-password}
  database: ${SNOWFLAKE_DATABASE:BKRISK_DB}
  schema: ${SNOWFLAKE_SCHEMA:CORE}
  warehouse: ${SNOWFLAKE_WAREHOUSE:COMPUTE_WH}

# optional: actuator if you want /health on backend
management:
  endpoints:
    web:
      exposure:
        include: health,info
