-- Snowflake setup for Banking Risk Platform
-- Run this in Snowflake to create the necessary database, schema, and table

-- Create database
CREATE DATABASE IF NOT EXISTS BKRISK_DB;

-- Create schema
CREATE SCHEMA IF NOT EXISTS BKRISK_DB.CORE;

-- Create loan applications table
CREATE TABLE IF NOT EXISTS BKRISK_DB.CORE.LOAN_APPLICATIONS (
    APPLICATION_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36),
    REVOLVING_UTILIZATION_OF_UNSECURED_LINES FLOAT,
    AGE INTEGER,
    NUMBER_OF_TIME_30_59_DAYS_PAST_DUE_NOT_WORSE INTEGER,
    DEBT_RATIO FLOAT,
    MONTHLY_INCOME FLOAT,
    NUMBER_OF_OPEN_CREDIT_LINES_AND_LOANS INTEGER,
    NUMBER_OF_TIMES_90_DAYS_LATE INTEGER,
    NUMBER_REAL_ESTATE_LOANS_OR_LINES INTEGER,
    NUMBER_OF_TIME_60_89_DAYS_PAST_DUE_NOT_WORSE INTEGER,
    NUMBER_OF_DEPENDENTS INTEGER,
    RISK_SCORE FLOAT,
    DECISION VARCHAR(10),
    SHAP_VALUES VARIANT,
    CREATED_AT TIMESTAMP_NTZ,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create a view for analytics (optional)
CREATE OR REPLACE VIEW BKRISK_DB.CORE.LOAN_APPLICATIONS_ANALYTICS AS
SELECT 
    APPLICATION_ID,
    USER_ID,
    REVOLVING_UTILIZATION_OF_UNSECURED_LINES,
    AGE,
    NUMBER_OF_TIME_30_59_DAYS_PAST_DUE_NOT_WORSE,
    DEBT_RATIO,
    MONTHLY_INCOME,
    NUMBER_OF_OPEN_CREDIT_LINES_AND_LOANS,
    NUMBER_OF_TIMES_90_DAYS_LATE,
    NUMBER_REAL_ESTATE_LOANS_OR_LINES,
    NUMBER_OF_TIME_60_89_DAYS_PAST_DUE_NOT_WORSE,
    NUMBER_OF_DEPENDENTS,
    RISK_SCORE,
    DECISION,
    SHAP_VALUES,
    CREATED_AT,
    LOADED_AT,
    -- Derived fields for analytics
    CASE WHEN DECISION = 'APPROVE' THEN 1 ELSE 0 END AS IS_APPROVED,
    CASE WHEN RISK_SCORE > 0.5 THEN 'HIGH_RISK'
         WHEN RISK_SCORE > 0.2 THEN 'MEDIUM_RISK'
         ELSE 'LOW_RISK' END AS RISK_CATEGORY,
    DATE(CREATED_AT) AS APPLICATION_DATE
FROM BKRISK_DB.CORE.LOAN_APPLICATIONS;

-- Grant permissions (adjust as needed)
GRANT USAGE ON DATABASE BKRISK_DB TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA BKRISK_DB.CORE TO ROLE PUBLIC;
GRANT SELECT, INSERT ON TABLE BKRISK_DB.CORE.LOAN_APPLICATIONS TO ROLE PUBLIC;
GRANT SELECT ON VIEW BKRISK_DB.CORE.LOAN_APPLICATIONS_ANALYTICS TO ROLE PUBLIC;
